""""Add_file_data_table"

Revision ID: 13a331e4b3cb
Revises: d3a5b6c7e8f9
Create Date: 2025-07-02 08:25:26.968990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a331e4b3cb'
down_revision: Union[str, Sequence[str], None] = 'd3a5b6c7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('id_huawei', sa.String(), nullable=True),
    sa.Column('cuid', sa.String(), nullable=True),
    sa.Column('mail_huawei', sa.String(), nullable=True),
    sa.Column('mail_orange', sa.String(), nullable=True),
    sa.Column('numero_telephone', sa.String(), nullable=True),
    sa.Column('domaine', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_data_id'), 'file_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_data_id'), table_name='file_data')
    op.drop_table('file_data')
    # ### end Alembic commands ###
